spring:
  datasource:
    url: jdbc:mariadb://database-1.c5fdh97vph8x.ap-northeast-2.rds.amazonaws.com:3306/simple__project_test?serverTimezone=Asia/Seoul
    username: admin
    password: dkssud22
    driver-class-name: org.mariadb.jdbc.Driver

    security:
      oauth2:
        client:
          registration:
            google:
              clientId: 1005346694436-2tromqpmnf2vnvoedk1d0btp42lgsgh7.apps.googleusercontent.com
              clientSecret: treyVcXPIhbvEGMe9oH3S7tx
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope: profile,email

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true


logging:
  level:
    me.silvernine: DEBUG
    org:
      hibernate:
        type: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpirationMsec: 864000000
